site:
  title: Decidim Docs
  url: https://docs.decidim.org
  start_page: v0.30@en:ROOT:index.adoc
content:
  sources:
    - url: &documentation .
      start_path: docs/en
      branches: [release/0.30-stable, HEAD]
      edit_url: "https://github.com/decidim/documentation/edit/{refname}/{path}"
    - url: &documentation .
      start_path: docs/fr
      branches: [develop]
    - url: &documentation .
      start_path: docs/es
      branches: [develop]
    - url: &documentation .
      start_path: docs/pt
      branches: [develop]
    - url: &documentation .
      start_path: docs/de
      branches: [develop]
    - url: https://github.com/decidim/decidim
      start_path: docs
      branches: [release/0.30-stable, HEAD]
ui:
  bundle:
    url: https://github.com/decidim/documentation-antora-ui/releases/download/v0.4/ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental_ui
antora:
  extensions:
    - require: '@antora/lunr-extension'
asciidoc:
  attributes:
    kroki-fetch-diagram: true
    page-pagination: ""
  extensions:
    - asciidoctor-kroki
    - asciidoctor-mathjax
